services:
  agente-rag:
    build: .
    container_name: agente-rag-corporativo
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
      - ./scripts:/app/scripts
      - ./src:/app/src
      - ./api:/app/api
      - /home/fifa/.cache/huggingface:/root/.cache/huggingface
      - /home/fifa/.cache/fastembed:/tmp/fastembed_cache
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TEMPERATURA=${TEMPERATURA}
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    restart: unless-stopped
